### PR TITLE
Implements "authentication"

### PR DESCRIPTION
**Pull request by chiaraDimension**
Implements authentication with OAuth 2, with a SSO login, sign-up, logout, user info, and end session.

See https://github.com/noi-techpark/it.bz.noi.community/issues/18

### CODE REVIEW

**Comment by chiaraDimension** [comment]
@Piiit I defined two different build variants:
- `development` -> uses testing machine authentication flow
- `production` -> uses production authentication flow
I changed accordingly the CI/CD job `build_and_deploy_to_play_store` to use production authentication flow:

Screenshot 2022-05-09 at 15 57 37

If you want to generate an app bundle for testing machine use case, you have to execute `./gradlew bundleDevelopmentRelease` command and retrieve the `.aab` file from `app/build/outputs/bundle/developmentRelease` directory. 

Similarly, if you want to generate the app file instead of the bundle:
- _development_
      - command: `./gradlew assembleDevelopmentRelease`
      - directory: `app/build/outputs/bundle/apk/development/release` 
- _production_
      - command: `./gradlew assembleProductionRelease`
      - directory: `app/build/outputs/bundle/apk/production/release` 

I left invariant the two tests jobs. From Gradle tasks documentation, we have that:
- test: Run unit tests for all variants
- connectedAndroidTest - Installs and runs instrumentation tests for all flavors on connected devices

If you want to run tests only for a specific variant, you can change the relative job with these possibilities:

`unit_tests` job:
testDevelopmentDebugUnitTest - Run unit tests for the developmentDebug build.
testDevelopmentReleaseUnitTest - Run unit tests for the developmentRelease build.
testProductionDebugUnitTest - Run unit tests for the productionDebug build.
testProductionReleaseUnitTest - Run unit tests for the productionRelease build.

`android_tests` job:
connectedDevelopmentDebugAndroidTest - Installs and runs the tests for developmentDebug on connected devices.
connectedProductionDebugAndroidTest - Installs and runs the tests for productionDebug on connected devices.
d

**Comment by chiaraDimension** [comment]
@MarE1991 , @pkritzinger 
Like in iOS version, the "my account" section as well as the "not authorised" window have a temporary UI. They will be adjusted in a successive PR.

my_account_tmp

access_not_granted_tmp

**Comment by chiaraDimension** [comment]
@MarE1991 I defined some new labels in [GSheet](https://docs.google.com/spreadsheets/d/1Yiol3UqS-0I9q4R5HLifVMdGbTSe3ZwuYBAMPyZJthc/edit#gid=0&range=A74:A78). Can you please check them and adding missing translations?

They refer to some errors that can occurs while
- loading user info from authentication system
- login/logout procedure

and that will be shown to user with appropriate alert dialogs, like these ones:

errore_profilo

errore_profilo_2

**Comment by chiaraDimension** [comment]
@Piiit can you please check this PR?

**Comment by Piiit** [comment]
@chiaraDimension @MarE1991 @pkritzinger Done, the new version with login should be available as soon as Google finished the review process...

New build version is 0.1.0.1652343810

**Pull request merged**
