### PR TITLE
book a room button

### LINKED ISSUE #86: Tab Orientate: change "book a room" button
Screenshot 2022-03-04 at 15 59 38

### PR DESCRIPTION
**Pull request by chiaraDimension**
Closes #86

### CODE REVIEW

**Comment by chiaraDimension** [comment]
book_a_room_with_icon

**Comment by Piiit** [comment]
@chiaraDimension Some checks fail, please fix them

**Comment by chiaraDimension** [comment]
See https://github.com/noi-techpark/it.bz.noi.community.android/pull/85

**Comment by Piiit** [comment]
@chiaraDimension  I merged the other PR, but now we have some conflicts, please rebase on top of "development" and fix the conflicts... Thank you

**Comment by chiaraDimension** [comment]
> @chiaraDimension I merged the other PR, but now we have some conflicts, please rebase on top of "development" and fix the conflicts... Thank you

Done

**Comment by Piiit** [comment]
Thx

**Pull request merged**
