### PR TITLE
Feature/bugfix

### PR DESCRIPTION
**Pull request by stezan**
Various fixes regarding the old app version. Improved shared data architecture.

### CODE REVIEW

**Comment by Piiit** [comment]
@stezan Hi, please fix the conflicts... thank you

**Comment by chiaraDimension** [comment]
> @stezan Hi, please fix the conflicts and errors shown in the unit_tests CI part... thank you

Fixed!

**Comment by Piiit** [comment]
@chiaraDimension Thx

**Comment by chiaraDimension** [comment]
> @chiaraDimension Thx

@Piiit can you please explain us when do you do the deploy? I see that 'build_and_deploy_to_play_store' job is always skipped, because it'd require [RELEASE] suffix in commit message. We'd like to understand build/deploy logic to know when we can check merged implementations.

**Comment by Piiit** [comment]
@chiaraDimension It is always deployed when we push to the development branch... the [RELEASE] tag is then pushed afterwards to have the same build number on github that we have on the store... so when I merge your PRs to development it gets always rolled out to the store and released for internal testers

**Comment by Piiit** [comment]
The build_and_deploy_to_play_store job is always skipped for all PRs and other branches other than "development"

**Comment by chiaraDimension** [comment]
@Piiit sorry, I missed `!` before `startsWith(github.event.head_commit.message, '[RELEASE]')`. Now it's clear. I was a bit confused because I didn't manage to see latest changes on app installed on my devices. But maybe the problem is relative to play store logics. Thanks.

**Pull request merged**
