### PR TITLE
Crash fix

### LINKED ISSUE #103: Crash with newest update
**Describe the bug**
The app crashes immediately after the last PR merge and update from 2022-05-25. Uninstalling and installing the app shows the login screen, but after the login we got crashes again.

**To Reproduce**
Steps to reproduce the first behavior:
1. Update to the newest version of the app (app must be already present on your phone)
2. Open it
3. See crash

Steps to reproduce the second behavior:
1. Uninstall and install the newest version of the app
2. Open it
3. Login
4. See crash

NB: Only the second behavior is visible in crashlytics, I guess the first crashes too early.

Got this traceback on my phone:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.feedback/com.google.android.feedback.FeedbackActivity}: java.lang.SecurityException: getDataNetworkTypeForSubscriber
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3761)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3935)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2286)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.SecurityException: getDataNetworkTypeForSubscriber
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:9300)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2971)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2935)
	at com.google.android.feedback.FeedbackSession.getTelephonyInfo(FeedbackSession.java:307)
	at com.google.android.feedback.FeedbackSession.<init>(FeedbackSession.java:152)
	at com.google.android.feedback.FeedbackSession.<init>(FeedbackSession.java:141)
	at com.google.android.feedback.FeedbackActivity.pushSession(FeedbackActivity.java:209)
	at com.google.android.feedback.FeedbackActivity.createFeedbackSession(FeedbackActivity.java:178)
	at com.google.android.feedback.FeedbackActivity.onCreate(FeedbackActivity.java:96)
	at android.app.Activity.performCreate(Activity.java:8241)
	at android.app.Activity.performCreate(Activity.java:8207)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3734)
	... 12 more

```

### PR DESCRIPTION
**Pull request by chiaraDimension**
Closes #103

### CODE REVIEW

**Comment by Piiit** [comment]
@chiaraDimension The CI fails, please have a look

**Comment by chiaraDimension** [comment]
> @chiaraDimension The CI fails, please have a look

Fixed!

I changed the jdk distribution in the _java setup_ step, because it wasn't able to install the previous jdk. Did you install some update on this machine?

**Comment by Piiit** [comment]
No this machine is always vanilla for each run, it is a node on Github

**Comment by Piiit** [comment]
Thx

**Pull request merged**
