### PR TITLE
filter screen

### LINKED ISSUE #16: Mapping of filter switches
Screenshot 2021-09-15 at 17 04 42

For every switch in the UI which is the correspondent parameter we should pass in the API of the events?

### PR DESCRIPTION
**Pull request by chiaraDimension**
Closes #16

### CODE REVIEW

**Comment by Piiit** [comment]
@chiaraDimension Please fix the issues shown during build steps:
```
* What went wrong:
Execution failed for task ':app:processReleaseGoogleServices'.
> Malformed root json
```

**Comment by chiaraDimension** [comment]
@Piiit it seems that _google-services.json_ file that is injected in the second step of `unit_test` job is malformed

**Comment by Piiit** [comment]
@chiaraDimension I will have a look at this issue today...

**Comment by Piiit** [comment]
@chiaraDimension merged manually

**Pull request closed without merging**
