### PR TITLE
News

### PR DESCRIPTION
**Pull request by chiaraDimension**
Closes https://github.com/noi-techpark/it.bz.noi.community.android/issues/91, https://github.com/noi-techpark/it.bz.noi.community.android/issues/92 and https://github.com/noi-techpark/it.bz.noi.community.android/issues/90

### CODE REVIEW

**Comment by chiaraDimension** [comment]
@MarE1991 we managed the news in the app. There are still some issues concerning some graphic aspects, in particular as regards the animations/transitions from the news/events list to detail page. These problems will be handle in another PR, sothat you can test the logic in the meantime.

**Comment by MarE1991** [comment]
> @MarE1991 we managed the news in the app. There are still some issues concerning some graphic aspects, in particular as regards the animations/transitions from the news/events list to detail page. These problems/enhancements will be handle in another PR, sothat you can test the logic in the meantime.

@chiaraDimension ok thanks! Is there a new version for android available where I can test it? In case, @Piiit can you send me the download link? THX

**Comment by chiaraDimension** [comment]
> > @MarE1991 we managed the news in the app. There are still some issues concerning some graphic aspects, in particular as regards the animations/transitions from the news/events list to detail page. These problems/enhancements will be handle in another PR, sothat you can test the logic in the meantime.
> 
> @chiaraDimension ok thanks! Is there a new version for android available where I can test it? In case, @Piiit can you send me the download link? THX

@Piiit will notify you as soon as it is available

**Comment by Piiit** [comment]
Hi all, the link is this one --> https://play.google.com/store/apps/details?id=it.bz.noi.community 

The new version should be available soon, Google is in review with the other release... 

I will merge this also, so we might get this release tomorrow or even later today.

As you all know, the update is not automatic (at least not in short time), so if you want to update your Android app, please open this link on your phone and see if an "Update" button is already available. 

You will get a login window first, so please (for those who have not already) send me your login email such that I can give you permissions to access the app...

Cheers
~piiit

**Comment by Piiit** [comment]
Strange placeholder image, but still mergeable ;-)

**Pull request merged**
