### PR TITLE
Feature/app skeleton

### PR DESCRIPTION
**Pull request by stezan**
First working version of the application. It only needs some little adjustments for the MVP1.

### CODE REVIEW

**Comment by stezan** [comment]
Hi @Piiit should i push a commit with the `[SNAPSHOT]` word to start the deployment? Or do you do it?

**Comment by Piiit** [comment]
@stezan We will remove the SNAPSHOT commit message rule and release on every push to the development branch in the future... 

I see that you have added some more commits, is this PR ready to be merged?

**Comment by stezan** [comment]
@Piiit yes it is ready, so we can start to collect feedback from internal tester

**Comment by stezan** [comment]
@Piiit can you add some of Dimensions email to Internal tester group?

**Comment by Piiit** [comment]
> @Piiit can you add some of Dimensions email to Internal tester group?

You are already present as an internal tester

**Comment by stezan** [comment]
Video

https://user-images.githubusercontent.com/22938515/134129429-5fa3a352-d8aa-487c-aaab-ae9b4f257ef7.mp4

**Comment by stezan** [comment]
> You are already present as an internal tester

@Piiit which emails did you add?

**Comment by Piiit** [comment]
dev@dimension.it

**Comment by Piiit** [comment]
The release pipeline failed... we will have a look at it asap

**Pull request merged**
